casdoor/casdoor-website

- .github/workflows/master.yml
> fix: Fix auto-publish of casdoor website

- docusaurus.config.js
> fix: Fix the baseUrl.

- .github/workflows/pr_ci.yml
- netlify.toml
> fix: Add netlify deploy and pr ci

- docs/provider/OAuth.md
- docs/provider/_category_.json
- docs/provider/email.md
- docs/provider/overview.md
- docs/provider/sms.md
Deployed at: https://casdoor.docs.chromium.link/docs/provider/overview
> feat: add provider intro

- docusaurus.config.js
I add some website configures and test the Netlify deploy preview.
Fix: #8 
> docs: Add Netlify deploy preview.

- .github/workflows/master.yml
- .gitignore
- crowdin.yml
- docusaurus.config.js
- package.json
- yarn.lock
> fix: Integrate Crowdin to support translations

- crowdin.yml
> fix: Fix failing checks

- crowdin.yml
> fix: Set api_token_env

- README.md
- src/pages/index.js
> docs: Add more content to README.

- docusaurus.config.js
> fix: Fix i18n failings

- docs/overview.md
- docusaurus.config.js
> docs: Add features to overview

- docusaurus.config.js
> feat: Add Baidu Analytics

- docs/application/_category_.json
- docs/application/overview.md
- docs/basic/_category_.json
- docs/basic/basic-concept-introduction.md
- docs/basic/installation.md
- docs/organization/_category_.json
- docs/organization/overview.md
- docs/provider/OAuth.md
- docs/provider/_category_.json
- docs/provider/overview.md
- docs/token/_category_.json
- docs/token/overview.md
- docs/user/_category_.json
- docs/user/overview.md
- sidebars.js
Signed-off-by: wasabi <690898835@qq.com>
> feat: optimized the casdoor website

- docusaurus.config.js
- package.json
- src/components/HomepageFeatures.js
- yarn.lock
Fix: [casbin/casdoor#147](https://github.com/casbin/casdoor/issues/147)
> feat: Upgrade docusaurus and fix typos

- package.json
- yarn.lock
> fix: Fix Crowdin failing

- docs/basic/installation.md
- docs/deploy/_category_.json
- docs/deploy/nginx.md
- sidebars.js
Fix: #23 
Signed-off-by: wasabi <690898835@qq.com>
> docs: add nginx section and improve installation section

- docs/application/overview.md
- docs/basic/installation.mdx
- docs/deploy/nginx.mdx
- docs/internationalization.md
- docs/provider/OAuth.md
- docs/provider/sms.md
- sidebars.js
> feat: Optimize docs and add translation part

- docs/basic/installation.mdx
- docs/deploy/nginx.mdx
> fix: Fix JSX caused failing

- docs/provider/OAuth.md
Signed-off-by: sh1luo <690898835@qq.com>
> fix: improve provider setup

- docs/basic/installation.mdx
Signed-off-by: killer <1533063601@qq.com>
> feat: add installation by docker

- docs/ldap/_category_.json
- docs/ldap/config.md
- docs/ldap/overview.md
- sidebars.js
Continue: https://github.com/casbin/casdoor/pull/160
Signed-off-by: WindSpiritSR <simon343riley@gmail.com>
> docs: add ldap docs

- docs/provider/OAuth.md
> docs: Add more OAuth provider setup

- docusaurus.config.js
> feat: Add sitemap

- src/pages/index.js
- src/pages/index.module.css
> fix: Fix button layout in homepage

- docusaurus.config.js
> feat: Add algolia docsearch

- package.json
- yarn.lock
> feat: Update docusaurus to beta4

- src/pages/index.js
- src/pages/index.module.css
> feat: Add Casdoor iframe to page

- docs/basic/installation.mdx
Signed-off-by: killer <1533063601@qq.com>
> fix: Emphasizes the precautions for docker installation

- docs/basic/basic-concept-introduction.md
- docs/basic/installation.mdx
Signed-off-by: sh1luo <690898835@qq.com>
> docs: improve installation

- docs/basic/SDKs.md
- sidebars.js
Fix: #29 
Signed-off-by: sh1luo <690898835@qq.com>
> docs: add sdk intro page

- src/pages/index.js
- src/pages/index.module.css
> fix: Modify lookings of iframe

- src/pages/index.module.css
> fix: Fix dark mode bug

- docs/provider/OAuth.md
- docs/provider/email.md
- docs/provider/sms.md
- docs/provider/storage.md
- sidebars.js
Signed-off-by: sh1luo <690898835@qq.com>
> docs: add storage section

- README.md
- docusaurus.config.js
1. Add hideable sidebar
2. Add auto-hide sticky navbar
> feat: Add more configurations

- docusaurus.config.js
- package.json
> fix: Fix code highlight bug

- docs/overview.mdx
- docs/styles.module.css
- src/pages/index.js
> docs: Add Casdoor iframe to docs

- docusaurus.config.js
- package.json
- src/pages/index.js
- src/pages/index.module.scss
- src/pages/markdown-page.md
- yarn.lock
> refactor: Change to sass styling

- src/pages/index.js
- src/pages/index.module.scss
Signed-off-by: 曲庆宇 <2283984853@qq.com>
> fix: Change Casdoor login iframe to forum signin iframe

- src/components/HomepageFeatures.js
- src/pages/index.js
> feat: Add homepage translate

- package.json
- src/theme/DocItem/index.js
- src/theme/DocItem/styles.module.css
- yarn.lock
> feat: Add Disqus

- package.json
- yarn.lock
> build: Update Docusaurus

- src/pages/index.module.scss
See the original page:
**After fixing:**
> fix: Fix view error on mobile

- docs/overview.mdx
docs: Update overview.mdx for more detailed usage explanation 
Signed-off-by: ffyuanda <shaoxuan.yuan02@gmail.com>
> docs: Update overview.mdx for more detailed usage explanation

- docs/basic/installation.mdx
> feat: Suggest users not to use npm

- docs/basic/installation.mdx
Relating commits:
https://github.com/casbin/casdoor/pull/311
https://github.com/casbin/casdoor/commit/ebc5fe454c0eface2d56686878e0e0dedc7fede6
> docs: Revise MySQL password

- docs/integration/_category_.json
- docs/integration/spring-boot.mdx
- sidebars.js
https://github.com/casdoor/casdoor-spring-boot-example/pull/3#issuecomment-963140767
Signed-off-by: “seriouszyx” <seriouszyx@foxmail.com>
> feat: add Spring Boot integration tutorial

- docs/basic/SDKs.md
> fix:update SDKs

- docs/integration/spring-boot.mdx
cause website render failed in chinese.
https://casdoor.org/zh/docs/integration/spring-boot/
> fix: fix syntax error

- docs/user/manipulation.md
- sidebars.js
TODO: Add an image illustrate the synchronization
> docs: Add user table bilateral synchronization

- docs/ldap/config.md
- docs/ldap/overview.md
docs: modify docs for ldap
Fix: https://github.com/casbin/casdoor/issues/359
> docs: modify docs for ldap

- docs/basic/installation.mdx
docs: add doc for all-in-one image
> docs: add doc for all-in-one image

- docs/integration/gitlab.md
Signed-off-by: 0x2a <stevesough@gmail.com>
> fix: wrong titile

- docs/integration/spring-boot.mdx
Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>
Update springboot integration doc using casdoor-spring-boot-starter.
> feat: update springboot integration doc

- docs/deploy/k8s.md
- sidebars.js
docs: add k8s deployments
Fix: https://github.com/casdoor/casdoor/issues/424
> docs: add k8s deployments

- docs/events/overview.md
- docs/provider/oauth/linkedin.md
Fix: https://github.com/casdoor/casdoor-website/issues/118
> fix: fixed typos (#118)

- docs/integration/elk.md
- sidebars.js
docs: add docs for casdoor/elk-auth-casdoor
Signed-off-by: Товарищ программист <2962928213@qq.com>
> docs: add docs for casdoor/elk-auth-casdoor

- docs/provider/oauth/overview.md
Signed-off-by: 0x2a <stevesough@gmail.com>
> feat: add steam doc

- docs/basic/try-with-docker.md
docs: add docker Engine requirements
> docs: add docker Engine requirements

- README.md
translate some docs 
Like:
https://casdoor.org/zh/docs/how-to-connect/access_token
https://casdoor.org/zh/docs/how-to-connect/sdk
https://casdoor.org/zh/docs/how-to-connect/oidc-client
https://casdoor.org/zh/docs/developer-guide/swagger
And:
https://casdoor.org/zh/docs/basic/core-concepts
https://casdoor.org/zh/docs/basic/try-with-docker
> docs: translate some docs

- README.md
https://casdoor.org/zh/docs/how-to-connect/sdk/
https://casdoor.org/zh/docs/basic/core-concepts
> docs: fix some format error

- README.md
- docs/basic/core-concepts.md
- package.json
- yarn.lock
add core concepts graph
add yarn markdown mermaid plugin
> docs: add core concepts graph

- docs/basic/server-installation.mdx
- docs/basic/try-with-docker.md
> docs: docs for configuration via env

- docs/integration/spring-boot.mdx
Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>
> feat: update spring boot integrations docs

- docs/basic/try-with-docker.md
> docs: revise docker docs

- docs/basic/try-with-docker.md
> fix: fix incorrect command

- docs/how-to-connect/cas.md
- docs/how-to-connect/overview.md
- sidebars.js
> feat: implement docs for cas

- docs/how-to-connect/access_token.md
Signed-off-by: 0x2a <stevesough@gmail.com>
> fix: authentication url error

- docs/integration/jenkins oidc.md
https://casdoor.org/zh/docs/integration/jenkins%20oidc
https://casdoor.org/zh/docs/basic/core-concepts/
> fix: fix some translation issues

- docs/how-to-connect/cas.md
> fix: add doc for cas 3.0

- docs/basic/try-with-docker.md
feat: add docker-compose  requirements
> feat: add docker-compose  requirements

- docs/basic/try-with-docker.md
docs: add alert for ali cloud accelerator
> docs: add warnings for alibaba cloud image booster

- docs/basic/server-installation.mdx
Made a few changes which enhances the readability of text.
> Updated docs/basic/server-installation.mdx

- src/pages/index.js
Fix: https://github.com/casdoor/casdoor-website/issues/214
Added a framemask component. When the user clicks, a mask layer will appear. Click to switch to the online demo.
https://user-images.githubusercontent.com/53009950/173488544-99ed3396-b602-47b2-b977-e22b38d9f63a.mp4
> fix:  add hyperlink to homepage's 3 iframes 

- docs/basic/server-installation.mdx
DB needs to be created manually.
> fix: modify server-installation.mdx about how to setup MySQL database

- docs/basic/server-installation.mdx
Fix: https://github.com/casdoor/casdoor-website/issues/229
> feat: update server-installation.mdx

- docs/provider/oauth/weCom.md
- sidebars.js
Fix: https://github.com/casdoor/casdoor-website/issues/240
> docs: add WeCom description

- docusaurus.config.js
- src/css/custom.css
Fix: https://github.com/casdoor/casdoor-website/issues/249
> feat: add announcementBar redirect to casbin

- package.json
- yarn.lock
fix: #248 
The latest docusaurus is 2.0.0-rc.1
> feat: Update docusaurus to the latest

- docs/basic/core-concepts.md
Fix: https://github.com/casdoor/casdoor-website/issues/253
Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>
> feat: add signin and signup URLs in docs

- docs/basic/try-with-docker.md
Fix: https://github.com/casdoor/casdoor-website/issues/254
> fix: improve try by docker docs

- docs/syncer/Database.md
- docs/syncer/overview.md
- docs/user/manipulation.md
- sidebars.js
Fix: https://github.com/casdoor/casdoor-website/issues/260
> docs: refactor manipulation page

- docs/contributing.md
- sidebars.js
Resolve: #263 
add contributor guide page
> docs: add contributor guide page

- docs/contributing.md
> docs: add modify PRs suggestion

- .github/workflows/pdf.yml
Preview:
https://github.com/Selflocking/casdoor-website/releases/tag/pdf
> feat: Export docs to PDF

- .github/workflows/pdf.yml
> fix: Draft releases is generated by default

- docs/basic/deployment.md
- docs/basic/server-installation.mdx
- sidebars.js
related: https://github.com/casdoor/casdoor/pull/1015
> docs: add depley static resoure guide

- docs/overview.mdx
- docs/styles.module.css
- src/pages/index.js
- src/pages/index.module.scss
Before:
https://casdoor.org/
After:
https://deploy-preview-290--iridescent-baklava-0d7550.netlify.app/
Before:
https://casdoor.org/docs/overview
After:
https://deploy-preview-290--iridescent-baklava-0d7550.netlify.app/docs/overview
Before:
https://casdoor.org/docs/application/config
After:
https://deploy-preview-290--iridescent-baklava-0d7550.netlify.app/docs/application/config
> fix: Improve iframe style

- src/pages/index.js
> fix: Only button can be clicked in iframe

- docusaurus.config.js
similar to https://github.com/casbin/casbin-website-v2/pull/79
> feat: Edit this page will jump to Crowdin when using non-English

- docs/basic/server-installation.mdx
- docs/basic/static-resource.md
Signed-off-by: magicwind <2814461814@qq.com>
> fix: update database and static resource deploy step

- docs/integration/wechat_miniprogram.md
Fix: casdoor/casdoor-wechat-miniprogram-example#1
> fix: update the usage of wechat miniprogram

- package.json
- src/theme/DocPaginator/index.js
- yarn.lock
> refactor: Switch to Giscus commenting system

- package.json
- yarn.lock
> chore: Remove useless dependencies

- docs/how-to-connect/oauth.md
resolve: https://github.com/casdoor/casdoor/issues/1059
> fix: improve how to add scope when get accesstoken

- docs/basic/try-with-docker.md
> docs: Add a note

- .eslintignore
- .eslintrc
- .stylelintignore
- .stylelintrc.json
- babel.config.js
- package.json
- src/components/HomepageFeatures.js
- src/css/custom.css
- src/pages/help.js
- src/pages/index.js
- src/pages/index.module.scss
- src/theme/DocPaginator/index.js
- static/js/gitter.js
- static/js/tawk.js
- yarn.lock
> feat: Add eslint and stylelint

- .husky/pre-commit
- package.json
- yarn.lock
Before commit, eslint and stylelint will be run to automatically check and try to fix style issues
> feat: Add pre-commit hook

- docs/how-to-connect/vue-sdk.md
- docs/integration/wechat_miniprogram.md
Fix: https://github.com/casdoor/casdoor-wechat-miniprogram-example/issues/5
> fix: improve Wechat miniprogram docs

- docs/application/config.md
- docs/overview.mdx
- package.json
- src/components/CasdoorCard/index.js
- src/pages/index.js
- src/pages/index.module.scss
- yarn.lock
> feat: Use the fastest demo site in docs

- sidebars.js
resolved: #336 
https://deploy-preview-341--iridescent-baklava-0d7550.netlify.app/docs/category/the-basics
> feat: generate index page for categories

- docs/basic/try-with-docker.md
> docs: start docker via environment variables

- docs/ldap/ldapserver.md
- sidebars.js
I implement the [ldap server](https://github.com/casdoor/casdoor/pull/1155) in casdoor, so I added this part of the documentation
> feat: add ldapserver docs

- src/components/CodeCard/index.js
- src/components/TabList/index.js
- src/components/TabList/styles.module.css
- src/pages/index.js
- src/pages/index.module.scss
> feat: add code editor to landing page

- docs/how-to-connect/overview.md
close: #369
Write more details to help user select one way to connect Casdoor.
> feat: tutorial and comparison of ways to connect Casdoor

- docs/deployment/db-migration.md
- sidebars.js
Fix: https://github.com/casdoor/casdoor-website/issues/371
> docs: Add DB Migration docs

- src/pages/index.js
> fix(FrameMask): The online demo has an error in the jump link

- .github/workflows/master.yml
- src/pages/pdf.js
> fix: wrong download link in pdf page

- docs/permission/adapter.md
Fix typos in: https://github.com/casdoor/casdoor-website/pull/408
> docs: typos

- docs/syncer/Database.md
- docs/syncer/overview.md
For: https://github.com/casdoor/casdoor/issues/1342#issuecomment-1334065351
> docs: improve syncer fields desciption

- docs/how-to-connect/sdk.md
> docs: change to clearer casdoor sdk link

- docs/application/config.md
- docs/overview.mdx
- docusaurus.config.js
- src/components/CasdoorCard/index.js
- src/components/NavbarItems/Casdoor.js
- src/pages/index.js
> refactor: use the single demo site

- docs/how-to-connect/sdk.md
> docs: change command language type

- docs/permission/overview.md
> Update casbin url

- docs/token/overview.md
Added information about the Token Format
> Describe JWT token types in token page

- src/css/custom.css
https://github.com/casbin/casbin-website-v2/pull/154
> fix: Sidebar expand button made visible

- docs/basic/server-installation.mdx
make sqlite create db file on disk and persistence saves data
> fix: Update sqlite command in server-installation.mdx

- docs/permission/exposed-casbin-apis.md
Fix: https://github.com/casdoor/casdoor/issues/1901
> docs: update Exposed Casbin APIs

- sidebars.js
https://docusaurus.io/docs/sidebar/items#expanded-categories-by-default
> fix: stop expanding categories below second level

- docs/basic/server-installation.mdx
see: https://github.com/casdoor/casdoor/blob/master/object/ormer.go#L27-L32
> docs: remove obsolete step

- docs/user/overview.md
https://github.com/casdoor/casdoor/issues/2282
> docs: add bypassing Password Encryption during user import

- docs/scim/overview.md
- sidebars.js
https://github.com/casdoor/casdoor/issues/2288
> docs: add doc for SCIM

- docs/basic/try-with-helm.md
from [#casdoor-helm](https://github.com/casdoor/casdoor-helm/pull/18)
Add more helm values following these.
- add envFromSecret
- add envFromConfigmap
- add envFrom
> docs: add envFrom to helm values

- README.md
> docs: fix yarn command in README.md

- docs/basic/server-installation.mdx
Please approve this fix, I spent 2 hours trying to figure this out
@jump2cn @dfang @hsluoyz @zh6335901 @joezhang-sh
> feat: Update server-installation.mdx about Postgres config

- docs/basic/try-with-helm.md
- Add link to casdoor charts docker hub
- Change the helm version to the latest
> docs: improve casdoor helm doc

- docs/token/overview.md
docs: add JWT-Standard format to token overview
> docs: add JWT-Standard format to token overview

- docs/ldap/config.md
docs: add default group field for ldap config
> docs: add default group

- docs/webhooks/overview.md
1. Provided a clearer explanation of webhooks and their event-driven nature.
2. Added a structured table for supported events.
3. Included a step-by-step guide on configuring webhooks in Casdoor.
4. Added a sample JSON payload for better understanding.
> docs: improved Casdoor webhooks documentation with setup and testing guide

- docs/how-to-connect/oauth.md
> docs: add device flow docs

- docs/provider/email/overview.md
docs: add docs for email content placeholder %link and  %{user.friendlyName}
> docs: add docs for email content placeholder

- docs/application/shared-application.md
Hey,
Noticed few minor spelling mistakes under the Shared Application documentation section.
> feat: fix minor spelling mistakes under Shared Application Section

- docs/deployment/docker.mdx
casdoor/casdoor does not exist on dockerhub, changed to casbin/casdoor
> feat: fix wrong DockerHub links

- docs/deployment/docker.mdx
Fix: https://github.com/casdoor/casdoor-website/issues/663
> docs: add SQLite note for Docker docs page

- docs/ldap/ldapserver.md
…ures and query examples
More information in casdoor#4013
Related PR: Casdoor#4014, Casdoor#4020
> feat: improve LDAP server docs
